### PR TITLE
Fix davx5 missing e-tag error.

### LINKED ISSUE #3: ETag with Android
Dear @sedenardi ! It me again.

I was trying to use your tool with android devices. Found out that they do not have native support for caldav protocol as iOS does.

So I did a research for the *most* acceptable open and free solution, for it, and discovered that there are only few stable, and one of most promising is the OpenSync. (https://play.google.com/store/apps/details?id=com.deependhulla.opensync)

However I had trouble in order to get it working, as it says something with ETag missing.

Can you provide any tip so that I can adjust it?

Thanks again!

--- BEGIN DEBUG INFO ---
SYNCHRONIZATION INFO
Synchronization phase: 8
Account name: user@ex
Authority: com.android.calendar

CURRENT REMOTE RESOURCE:
https://192.168.100.11:3001/caldav/cal/user@ex.co/exampleCal2/EE6BCBAF-C85B-49F5-A5C4-6EFB9F5090FF.ics

EXCEPTION:
at.bitfire.dav4android.exception.DavException: Server didn't provide ETag
	at com.deependhulla.opensync.syncadapter.SyncManager.compareLocalRemote(SyncManager.java:439)
	at com.deependhulla.opensync.syncadapter.SyncManager.performSync(SyncManager.java:175)
	at com.deependhulla.opensync.syncadapter.CalendarsSyncAdapterService$SyncAdapter.onPerformSync(CalendarsSyncAdapterService.java:70)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)

SOFTWARE INFORMATION
OpenSync version: 1.5.0.3-ose (145) Tue Apr 18 04:03:24 GMT-03:00 2017
Installed from: com.android.vending
JB Workaround installed: no

CONFIGURATION
Power saving disabled: no
android.permission.READ_CONTACTS permission: denied
android.permission.WRITE_CONTACTS permission: denied
android.permission.READ_CALENDAR permission: granted
android.permission.WRITE_CALENDAR permission: granted
org.dmfs.permission.READ_TASKS permission: denied
org.dmfs.permission.WRITE_TASKS permission: denied
System-wide synchronization: automatically
Account: user@ex
  Address book sync. interval: —
  Calendar     sync. interval: 240 min
  OpenTasks    sync. interval: —
  WiFi only: false
  [CardDAV] Contact group method: GROUP_VCARDS
  [CalDAV] Time range (past days): 90
           Manage calendar colors: true

SQLITE DUMP
android_metadata
	|  locale |
	|  ***** |
----------
settings
	|  setting | value |
----------
services
	|  _id | accountName | service | principal |
	|  1 | user@ex | caldav | https://192.168.100.11:3001/caldav/p/user@ex.co/ |
----------
sqlite_sequence
	|  name | seq |
	|  services | 1 |
	|  homesets | 2 |
	|  collections | 2 |
----------
homesets
	|  _id | serviceID | url |
	|  2 | 1 | https://192.168.100.11:3001/caldav/cal/user@ex.co/ |
----------
collections
	|  _id | serviceID | url | readOnly | displayName | description | color | timezone | supportsVEVENT | supportsVTODO | sync |
	|  1 | 1 | https://192.168.100.11:3001/caldav/cal/user@ex.co/exampleCal2/ | 0 | Example Calendar 2 | <null> | <null> | <null> | 1 | 0 | 1 |
	|  2 | 1 | https://192.168.100.11:3001/caldav/cal/user@ex.co/exampleCal1/ | 1 | Example Calendar 1 | <null> | <null> | <null> | 1 | 0 | 0 |
----------

SYSTEM INFORMATION
Android version: 10 (QP1A.190711.020.A705MNXXU5BTC2)
Device: Samsung SM-A705MN (a70q)

--- END DEBUG INFO ---

### PR DESCRIPTION
**Pull request by aharter**
This PR should fix #3, #6 and #8.

I haven't checked the RFC, so I'm not sure if this is according to standard. Especially the filter functions. Which is why I opened it as a draft. Let's discuss.

### CODE REVIEW

**Comment by HeikoTheissen** [comment]
This fixes the two problems I reported in my comments.

File: src/common/xBuild.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@ type XmlElement = {
   [tag: string]: any;
 };
 
-const nsMap = mapKeys(namespaces, (v, k) => {
+const nsMap = () => mapKeys(namespaces, (v, k) => {
```
Comment (sedenardi) [inline src/common/xBuild.ts:9]: Is the change to make this a function that returns the `nsMap` object because it was being modified in the responses over multiple `multistatus` function calls?

File: example/data.js [hunk 2]
```diff
@@ -73,6 +73,22 @@ const bumpSyncToken = function(cal) {
   cal.syncToken = parts.slice(0, -1).join('/') + '/' + (parseInt(parts[parts.length - 1]) + 1);
 };
 
+const eventFilter = (start, end, eventStart, eventEnd) =>
```
Comment (sedenardi) [inline example/data.js:76]: Please match the coding style of this repository and only use arrow functions for anonymous callback functions.

File: example/data.js [hunk 3]
```diff
@@ -73,6 +73,22 @@ const bumpSyncToken = function(cal) {
...
+  (!end || end < eventStart) || (!start || start > eventEnd)
+
+const recurringEventFilter = (start, end, event) => {
```
Comment (sedenardi) [inline example/data.js:79]: If possible, please add types to function parameters.

File: example/data.js [hunk 4]
```diff
@@ -73,6 +73,22 @@ const bumpSyncToken = function(cal) {
...
+  if (!event.recurring) {
+    return false;
+  }
+
+  const eventStart = event.startDate
```
Comment (sedenardi) [inline example/data.js:84]: Please match the coding style of the repository and include semicolons at the end of statements.

**Review by sedenardi — CHANGES_REQUESTED** [review]

**Comment by sedenardi** [comment]
Thanks for the PR, sorry for the delay in reviewing. A few things:

- Can you post the request and response bodies before and after this change so we can ensure they're still conforming to the RFC?
- There are a few coding style changes that need to be made to make the PR code consistent with the rest of the repository.

File: src/common/xBuild.ts (hunk 1 above)
Comment (aharter) [reply src/common/xBuild.ts:9]: Yes. The changes modified the map inplace and by creating a new map each time, this is prevented.

File: example/data.js (hunk 3 above)
Comment (aharter) [reply example/data.js:79]: This is a `js`file, I therefore omitted the typing. Just like the other functions do in this file, too.
I'm guess it would make sense to rewrite this file and use `ts-node` to execute it. I guess a change for another PR

File: example/data.js (hunk 4 above)
Comment (aharter) [reply example/data.js:84]: Seems like `eslint` is not linting the example files. I can add a commit or create a new PR to solve this. What do you think?

**Comment by aharter** [comment]
I made the requested style changes.

Here is the before and after comparison of request/response:
**REQUEST PROPFIND /caldav/cal/user@ex.co/exampleCal1/**
```xml
<?xml version='1.0' encoding='UTF-8' ?>
<CAL:calendar-query xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav">
  <prop>
    <getetag />
  </prop>
  <CAL:filter>
    <CAL:comp-filter name="VCALENDAR">
      <CAL:comp-filter name="VEVENT">
        <CAL:time-range start="20201004T154527Z" />
      </CAL:comp-filter>
    </CAL:comp-filter>
  </CAL:filter>
</CAL:calendar-query>
```

**RESPONSE BEFORE**
```xml
<?xml version="1.0"?>
<D:multistatus xmlns:D="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/" xmlns:ICAL="http://apple.com/ns/ical/">
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
      <D:prop>
        <D:supported-report-set>
          <D:supported-report>
            <D:report>
              <CAL:calendar-query/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <CAL:calendar-multiget/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <CAL:sync-collection/>
            </D:report>
          </D:supported-report>
        </D:supported-report-set>
      </D:prop>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/41c6fcc0-aea7-304f-983a-a6fb7e568109.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/faf52014-372e-44ed-9eba-2fc1a2b8d82d.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/895a04b2-30df-4927-ba03-dfc55514f6e7.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/30946424-40f4-47e2-80b1-006fdebbeb25.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>
```

**RESPONSE AFTER**
```xml
<?xml version="1.0"?>
<D:multistatus xmlns:D="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/" xmlns:ICAL="http://apple.com/ns/ical/">
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/41c6fcc0-aea7-304f-983a-a6fb7e568109.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
      <D:prop>
        <D:getetag>20201122T100456Z</D:getetag>
      </D:prop>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/faf52014-372e-44ed-9eba-2fc1a2b8d82d.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
      <D:prop>
        <D:getetag>20201122T100456Z</D:getetag>
      </D:prop>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/895a04b2-30df-4927-ba03-dfc55514f6e7.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
      <D:prop>
        <D:getetag>20201122T100456Z</D:getetag>
      </D:prop>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/30946424-40f4-47e2-80b1-006fdebbeb25.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
      <D:prop>
        <D:getetag>20201122T100456Z</D:getetag>
      </D:prop>
    </D:propstat>
  </D:response>
</D:multistatus>
```

**Note**
The missing parts in the `before` response (with `<D:supported-report-set>`) was generated by the previous request

File: example/data.js (hunk 2 above)
Comment (aharter) [reply example/data.js:76]: Should this be documented in the `README` under `Contributing`. Or is this covered by eslint?

**Comment by sedenardi** [comment]
Apologies for the delay in reviewing this, I'll take some time in the next few days to take a look and give my feedback.

File: example/data.js (hunk 3 above)
Comment (sedenardi) [reply example/data.js]: Ahh my mistake.

**Comment by sedenardi** [comment]
@aharter When I use `curl` to send the request in your example, I can't reproduce your findings. The responses on `master` and your branch are identical.

#### curl request

```sh
curl \
  --request PROPFIND \
  -H "Content-Type: text/xml" \
  --compressed \
  --url "http://localhost/caldav/cal/user@ex.co/exampleCal1/" \
  -u "user@ex.co:pass" \
  --data-binary @- << EOF
<?xml version='1.0' encoding='UTF-8' ?>
<CAL:calendar-query xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav">
  <prop>
    <getetag />
  </prop>
  <CAL:filter>
    <CAL:comp-filter name="VCALENDAR">
      <CAL:comp-filter name="VEVENT">
        <CAL:time-range start="20201004T154527Z" />
      </CAL:comp-filter>
    </CAL:comp-filter>
  </CAL:filter>
</CAL:calendar-query>
EOF
```

#### Response

```xml
<?xml version="1.0"?>
<D:multistatus xmlns:D="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/" xmlns:ICAL="http://apple.com/ns/ical/">
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 404 Not Found</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/41c6fcc0-aea7-304f-983a-a6fb7e568109.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/faf52014-372e-44ed-9eba-2fc1a2b8d82d.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal1/895a04b2-30df-4927-ba03-dfc55514f6e7.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>
```

A couple things I noticed in the request

- `<prop>` should be `<A:prop>`, right? Did you write the request, or did it come from the app?
- `<getetag />` should be `<A:getetag />` - same as above

but changing those doesn't seem to have any effect.

The `getetag` element isn't being parsed properly, because it's not in the [element array](https://github.com/sedenardi/node-caldav-adapter/blob/master/src/routes/calendar/calendar/propfind.ts#L35) when the XML body is parsed.

However, the `etag` _is_ present in the response when I make this request:

#### curl request

```sh
curl \
  --request PROPFIND \
  -H "Content-Type: text/xml" \
  --compressed \
  --url "http://localhost:3001/caldav/cal/user@ex.co/exampleCal2/" \
  -u "user@ex.co:pass" \
  --data-binary @- << EOF
<?xml version="1.0" encoding="UTF-8"?>
<A:propfind xmlns:A="DAV:">
  <A:prop>
    <A:getcontenttype/>
    <A:getetag/>
  </A:prop>
</A:propfind>
EOF
```

#### response

```xml
<?xml version="1.0"?>
<D:multistatus xmlns:D="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/" xmlns:ICAL="http://apple.com/ns/ical/">
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal2/</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
      <D:prop>
        <D:getcontenttype>text/calendar; charset=utf-8; component=VEVENT</D:getcontenttype>
      </D:prop>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal2/b5292608-2548-0041-8d7a-d7d6257d0b58.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
      <D:prop>
        <D:getcontenttype>text/calendar; charset=utf-8; component=VEVENT</D:getcontenttype>
        <D:getetag>20210205T043707Z</D:getetag>
      </D:prop>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal2/a3f14917-7607-d94b-bcd8-1d0a9cf408f8.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
      <D:prop>
        <D:getcontenttype>text/calendar; charset=utf-8; component=VEVENT</D:getcontenttype>
        <D:getetag>20210205T043707Z</D:getetag>
      </D:prop>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/caldav/cal/user@ex.co/exampleCal2/30946424-40f4-47e2-80b1-006fdebbeb25.ics</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
      <D:prop>
        <D:getcontenttype>text/calendar; charset=utf-8; component=VEVENT</D:getcontenttype>
        <D:getetag>20210205T043707Z</D:getetag>
      </D:prop>
    </D:propstat>
  </D:response>
</D:multistatus>
```

So it's either I'm incorrectly implementing the RFC (by looking for `prop` elements only if they're nested in a `propfind` element), or whatever client you're using is sending improper requests.

To be clear, I largely wrote this library based on the requests and responses that the MacOS/iOS clients send, and used the RFC as as clarifying guide. I'll try to dig into the RFC later on and see whether I should be considering `prop` element requests when not nested inside of a `propfind` element request, but I encourage you to do so as well.

I also apologize again for the long delay. Work mixed with having to re-familiarize myself with the library, as I haven't done significant work on it since middle of 2019.

File: src/common/xBuild.ts (hunk 1 above)
Comment (HeikoTheissen) [inline src/common/xBuild.ts:9]: @sedenardi, to verify that this change is necessary, first request
```
curl -i -L -X REPORT \
   -H "Content-Type:application/xml" \
   -d \
'<?xml version="1.0" encoding="UTF-8"?>
<L:calendar-query xmlns:L="urn:ietf:params:xml:ns:caldav">
  <D:prop xmlns:D="DAV:">
    <D:getcontenttype/>
    <D:getetag/>
    <L:calendar-data/>
  </D:prop>
  <L:filter>
    <L:comp-filter name="VCALENDAR">
      <L:comp-filter name="VEVENT">
        <L:time-range start="20181025T000000Z"/>
      </L:comp-filter>
    </L:comp-filter>
  </L:filter>
</L:calendar-query>' \
 'http://localhost:3001/caldav/cal/user@ex.co/exampleCal1'
```
and then repeat the request with
```
<L:time-range start="20281025T000000Z"/>
```
The first request should return three events, the second none. But prior to @aharter's change, the second request gave the same response as the first, because `nsMap` had the same value on both occasions.

Comment (sedenardi) [reply src/common/xBuild.ts:9]: Ahh. So the issue is before the change, the response for both of your requests returns 0 events:

```xml
<?xml version="1.0"?>
<D:multistatus xmlns:D="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/" xmlns:ICAL="http://apple.com/ns/ical/"/>
```

Whereas with this PR, the first request correctly returns 3 events, and the second request correctly returns 0 events.

Comment (sedenardi) [inline src/common/xBuild.ts:9]: Please make this a regular function, rather than an arrow function. Convention of this library only uses arrow functions for anonymous callback functions.

**Comment by sedenardi** [comment]
I've tested this PR with MacOS and iOS, and everything looks good. I made a small comment regarding code conventions, but other than that it looks ready to mark as "Ready for review". Once you've done that I'll do another pass and merge if accepted.

Thanks again for your help and patience.

**Comment by aharter** [comment]
Thanks for taking the time to review the PR. I resolved your comments, if you have further additions please let me know.
Next step for me would be figuring out, whether I port my application to koa or create some PR support expressjs. I guess for the later your thoughts around it would be crucial.

File: src/common/xBuild.ts [hunk 5]
```diff
@@ -6,9 +6,11 @@ type XmlElement = {
...
 };
 
-const nsMap = mapKeys(namespaces, (v, k) => {
-  return `@xmlns:${k}`;
-});
+const nsMap = function() {
+  return mapKeys(namespaces, (v, k) => {
+    return `@xmlns:${k}`;
+  });
+}
```
Comment (HeikoTheissen) [inline src/common/xBuild.ts:13]:
```suggestion
};
```
Missing semicolon leads to build error
```
  13:2  error  Missing semicolon  @typescript-eslint/semi
```

**Review by HeikoTheissen — CHANGES_REQUESTED** [review]

File: src/common/xBuild.ts (hunk 5 above)
Comment (aharter) [reply src/common/xBuild.ts:13]: :facepalm: That's what I get for thinking "hey, I have 5 min to spare. Let's fix this real quick"

Thanks for noticing.

**Review by HeikoTheissen — APPROVED** [review]

**Review by sedenardi — APPROVED** [review]

**Comment by sedenardi** [comment]
@aharter @HeikoTheissen Thanks to you both for your contributions. I've just published a new version to `npm` at `4.2.0`.

> Next step for me would be figuring out, whether I port my application to koa or create some PR support expressjs. I guess for the later your thoughts around it would be crucial.

I originally wrote the library with intention to expand it with express middleware support. It wouldn't take too much work to generalize the route and method handler functions to take in an object with context/request fields (not exhaustive):

- method
- url
- params (raw and parsed)
- authenticated user

and I'd certainly support such an effort if you wanted to take it on.
